### ISSUE TITLE
what is the purpose of the school query parameter?

### ISSUE THREAD

**Issue by aryarm** [MuddCreates/hyperschedule-scraper#14]
Hey guys,

I just got started using the Hyperschedule API. It's fantastic! I really appreciate that something like this exists. It certainly made my life a lot easier.

I have just one quick question so far:
It doesn't seem like changing the `school` parameter value (for example, from `hmc` to `cmc`) will alter the data returned by the API. So what is its purpose? Why do you require a value for it?

Feel free to close this issue without a response if I'm just misunderstanding something basic. Admittedly, I have not taken a detailed look into your source code in search of an answer yet.

**Comment by kwshi** [comment]
Good question!  I believe the school parameter you are referring to is there to (eventually) support having separate databases for other, non-5C schools.  For our purposes, all 5C colleges count as the same “school” from the perspective of Hyperschedule’s API.

**Comment by aryarm** [comment]
Ah ok that makes sense
Thanks again for making such a great API!
