### ISSUE TITLE
Separate server.py code into modules

### ISSUE THREAD

**Issue by ssantichaivekin** [MuddCreates/hyperschedule-scraper#5]
I propose that the file be separated into the following modules:
1. **Server**: Logic about serving the json files to the client.
2. **Portal Scraper**: contains logic about obtaining the raw json file from the portal by web-scraping. Also contains logic of how to convert that raw file into the format recognized by hyperschedule.
3. **Incremental Updates**: contains the logic of computing the difference of course data and updating them.
4. **Lingk Scraper**: we should make a new module when lingk is incorporated to the code.

Do you guys agree with this proposal? Or do you think we should have less modules (or more)?

**Comment by raxod502** [comment]
I don't see anything wrong with that.

**Comment by raxod502** [comment]
I modularized the backend.
